pipeline:
  build:
      image: rust:1.30
      commands:
        - cargo install mdzk
  deploy:
    image: drillster/drone-rsync
    hosts: [ "192.168.1.5" ]
    port: 3471
    target: /var/www/html/wiki.fr1nge.xyz
    source: public/*
    key:
      from_secret: rsync_key
    user: root
    secrets: [ rsync_key ]
