pipeline:
  excalidraw:
    image: python
    commands:
      - python excalidrawtosvg.py
  structure:
    image: python
    commands:
      - pip install -r requirements.txt
      - python3 genstructure.py release
  build:
      image: fr1nge/mdzk:latest
      commands:
        - mdzk build
  deploy:
    image: drillster/drone-rsync
    hosts: [ "192.168.1.5" ]
    port: 3471
    delete: true
    recursive: true
    target: /var/www/html/wiki.fr1nge.xyz
    source: html/
    key:
      from_secret: rsync_key
    user: root
    secrets: [ rsync_key ]
