[mdzk]
authors = ["Yigit Colakoglu"]
ignore = ["Excalidraw", "Images"]
language = "en"
multilingual = false
src = "notes"
title = "Obsidian Wiki"
description = "An online version of my Zettelkasten"

[output.html.fold]
enable = true
level = 1

[build]
preprocessors = ["mermaid"]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
