[mdzk]
authors = ["Yigit Colakoglu"]
ignore = ["Excalidraw", "Images", "index"]
language = "en"
multilingual = false
src = "notes"
title = "Obsidian Wiki"
description = "An online version of my Zettelkasten"
